### ISSUE TITLE
主从复制

### ISSUE THREAD

**Issue by huerni** [go-gorm/dbresolver#116]
## 从库会自动更新吗？
请问使用更新语句时，从库会自动更新吗？当我AutoMigrate表，insert数据时，主库有表和数据，从库没有任何动作，然后读是从从库中读，所以读不到数据，请问是为什么呢

**Comment by ZheruiL** [comment]
数据库主从同步是在数据库里设置的，不是gorm控制的。。。具体如何设置可以参考 https://www.cnblogs.com/haima/p/14341903.html

**Comment by huerni** [comment]
哦哦哦，我第一次接触这个，谢谢了
