### ISSUE TITLE
Use dr.Call() without datas into db.Register(config, datas...)

### ISSUE THREAD

**Issue by Harv3009** [go-gorm/dbresolver#14]
Hi! Can i use dr.Call without datas in db.Register(config, datas...) ?

Callback is called if resolvers is not empty or called db.Register()

```
func (dr *DBResolver) Call(fc func(connPool gorm.ConnPool) error) error {
	if dr.DB != nil {
		for _, r := range dr.resolvers {
			if err := r.call(fc); err != nil {
				return err
			}
		}
	} else {
		dr.compileCallbacks = append(dr.compileCallbacks, fc)
	}

	return nil
}
```

I wanted to close the connections with dr.Call after db.Use(dbresolver)

**Comment by jinzhu** [comment]
https://gorm.io/docs/connecting_to_the_database.html#Existing-database-connection
