### ISSUE TITLE
incompatible with gorm v1.25.12

### ISSUE THREAD

**Issue by EvisuXiao** [go-gorm/dbresolver#145]
## GORM Playground Link

https://github.com/go-gorm/gorm/pull/7142

## Description

current dbresolver tag: v1.5.2

When I upgrade go-gorm to the latest tag (v1.25.12), i can't launch my project. I has previewed the changelog and i found an issue https://github.com/go-gorm/gorm/pull/7142/files ,which fixs a problem of memory leaks.But it had removed a field "**PreparedSQL**" from struct "**PreparedStmtDB**".
Unfortunately, gorm dbresolver is using this field currently ([dbresolver.go](https://github.com/go-gorm/dbresolver/blob/6d95870e4207bbd2a7895fb142492405271804db/dbresolver.go#L147) at line 147), it seems initialed only and not referred by other function, we can remove it too.
It's confused to me, i can't upgrade gorm to the latest until the breaking change has been fixed. Could u help me, thanks a lot.

**Comment by smalls0098** [comment]
go.mod添加一行
replace gorm.io/plugin/dbresolver v1.5.2 => github.com/smalls0098/dbresolver v0.0.0-20240909115957-b928cd627cd8
临时解决，等待修复
<img width="968" alt="image" src="https://github.com/user-attachments/assets/ef6d3f4d-627f-4cb5-81bb-979e773f8de9">

**Comment by a631807682** [comment]
upgrade to v1.5.3
