### ISSUE TITLE
Due to fixing the memory leak problems, PreparedSQL field was removed in gorm repo, but this repo still references the problematic gorm version v1.25.11. Can you consider upgrading the dependent Gorm version?

### ISSUE THREAD

**Issue by floatyun** [go-gorm/dbresolver#147]
i followed the gorm [doc](https://gorm.io/docs/connecting_to_the_database.html#PostgreSQL) code
```go
import (
  "gorm.io/driver/postgres"
  "gorm.io/gorm"
)

dsn := "host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable TimeZone=Asia/Shanghai"
db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
```
However, when i build, go complained as follows.
```txt
# gorm.io/plugin/dbresolver
..\..\..\..\go\pkg\mod\gorm.io\plugin\dbresolver@v1.5.0\dbresolver.go:147:5: unknown field PreparedSQL in struct literal of type gorm.PreparedStmtDB
```
After some searching and analysis, I found that the problem lies in the gorm repository v1.15.11, which was updated to v1.15.12 due to fixing a memory leak issue. And during this repair, the `PreparedSQL` field for `PreparedStmtDB` struct, which in `gorm.io/gorm/prepare_stmt.go` was removed.
![image](https://github.com/user-attachments/assets/b6e2dbba-d022-47f2-9240-f86c2d010cf6)
However in this repo, still use the old gorm version(v1.25.7)
At present, i specify the particular older gorm version to ensure my project build successfully. But since the update is a bug fix, I hope this repo can be upgraded accordingly.

**Comment by yyle88** [comment]
```
unknown field PreparedSQL in struct literal of type gorm.PreparedStmtDB
```

Can you consider upgrading the dependent Gorm version.

**Comment by flc1125** [comment]
https://github.com/go-gorm/dbresolver/pull/144

**Comment by a631807682** [comment]
upgrade to v1.5.3
