### ISSUE TITLE
I want to be able to enable read replicas for transactions as well

### ISSUE THREAD

**Issue by kostyay** [go-gorm/dbresolver#15]
## Describe the feature

We are using ROW LEVEL SECURITY to achieve multi tenancy. Since RLS is based on transactions we are unable to utilize the read replicas feature as it always forwards the connections to the write replica.
We would like to be able to control this behavior via some flag to the query operation.

**Comment by raja** [comment]
@kostyay Were you able to workaround this limitation?

**Comment by jinzhu** [comment]
We have added support for transaction, thank you for your report.
