### ISSUE TITLE
How can I close the replicas connections

### ISSUE THREAD

**Issue by Kis-Chuan** [go-gorm/dbresolver#45]

**Comment by jinzhu** [comment]
you can't, and most likely not necessary. maybe you can change the pool size to achieve your goal.

**Comment by isaacwein** [comment]
how with changing the pool size can i gracefully close all mysql instance

with out dbresolver i can call gorm.DB() it will give me back the the mysql instance. 

with dbresolver  you only get back 1 mysql i can close that but how do i loop on all mysql instances to close them
