### ISSUE TITLE
multi source write

### ISSUE THREAD

**Issue by qianxiansheng90** [go-gorm/dbresolver#65]
clickhouse 通过 distribute engine表可以实现分布式写。
`
        dsn1 := "192.168.1.1:9000"
	dsn2 := "192.168.1.2:9000"
	dsn3 := "192.168.1.3:9000"
	dsn4 := "192.168.1.4:9000"

	dbConn, err := gorm.Open(clickhouse.Open(dsn1), &gorm.Config{
		SkipDefaultTransaction: true,
	})
	if err != nil {
		fmt.Println(err)
		return
	}

	err = dbConn.Use(dbresolver.Register(dbresolver.Config{
		// `db2` 作为 sources，`db3`、`db4` 作为 replicas
		Sources: []gorm.Dialector{clickhouse.Open(dsn2), clickhouse.Open(dsn1), clickhouse.Open(dsn3), clickhouse.Open(dsn4)},
		// sources/replicas 负载均衡策略
		Policy: dbresolver.RandomPolicy{},
	}))
	if err != nil {
		fmt.Println(err)
		return
	}

   # write data
	err = dbConn.Transaction(func(tx *gorm.DB) error {
		if err = tx.Create(&[]module.Tbl{t}).Error; err != nil {
			return err
		}
		// 返回 nil 提交事务
		return nil
	})

`
有四个clickhouse实例构建一套集群，使用dbConn 写入 数据库的时候发现始终是通过 dsn1，读取可以通过四个dsn读取，这个是为什么？
期望：写入也是可以根据随机选取

**Comment by jinzhu** [comment]
https://github.com/go-gorm/dbresolver/commit/8866a192edd1d6cf4915640fd78883f04b7628f2

**Comment by jinzhu** [comment]
err = dbConn.Clauses(dbresolver.Write).Transaction(func(tx *gorm.DB) error {
	if err = tx.Create(&[]module.Tbl{t}).Error; err != nil {
		return err
	}
	// 返回 nil 提交事务
	return nil
})
