### ISSUE TITLE
Updating from v1.1.0 to v1.2.0 may cause "runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by mgsweet** [go-gorm/dbresolver#73]
## Description
Updating from v1.1.0 to v1.2.0 may cause panic because of the following line:
https://github.com/go-gorm/dbresolver/blob/691098d97114834990003c8f6040f2b20148bb8d/clauses.go#L49

`Get("gorm:db_resolver")` would return `nil` if `db_resolver` is not set up correctly, which would cause "runtime error: invalid memory address or nil pointer dereference".

**Comment by jinzhu** [comment]
Fixed that.
