### ISSUE TITLE
For Read/Write splitting, allow logging of which DSN each query goes to

### ISSUE THREAD

**Issue by gcaragea** [go-gorm/dbresolver#75]
## Describe the feature

I am using the Read/Write splitting feature. I would like to log for each query which DSN it goes to (or at least if it goes to a source or replica).

## Motivation

This would be used for troubleshooting failed or slow DB instances, and for testing.

## Related Issues

N/A.

**Comment by seon1-kim** [comment]
+1

**Comment by JellyZero** [comment]
+1 @jinzhu

**Comment by santiago-correa-asapp** [comment]
+1

**Comment by jasonzbao** [comment]
+1
