### ISSUE TITLE
dbresolver v1.2.3编译错误

### ISSUE THREAD

**Issue by zsy619** [go-gorm/dbresolver#84]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

go.mod引用：
```go
	gorm.io/gen v0.3.16
	gorm.io/gorm v1.24.0
	gorm.io/plugin/dbresolver v1.2.3
```
编译出现如下错误：
```shell
2022/10/08 10:15:38 ERROR    ▶ 0006 Failed to build the application: # gorm.io/plugin/dbresolver
/go/pkg/mod/gorm.io/plugin/dbresolver@v1.2.3/dbresolver.go:139:18: 
cannot use map[string]gorm.Stmt{} (value of type map[string]gorm.Stmt) as type map[string]*gorm.Stmt in struct literal
```
截图如下：
![image](https://user-images.githubusercontent.com/6278792/194683335-b93addb1-15bc-4022-a840-42293c2f1d77.png)

**Comment by zsy619** [comment]
gorm v1.24.0这个版本有问题，降级到 v1.23.0 可以编译通过
帮忙看下是不是gorm最新版本与dbresolver v1.2.3版本冲突

**Comment by zsy619** [comment]
看了下gen项目，引用如下：
```go
	gorm.io/gorm v1.23.9-0.20220713102635-3262daf8d468
	gorm.io/hints v1.1.0
	gorm.io/plugin/dbresolver v1.2.2
```
也就是gen没有引用最新的类库引起的，需要对gen项目进行修订

**Comment by bohehe** [comment]
Confirmed resolved in latest release v1.3.0, thank you. @jinzhu
